print("TEST")
#configfile: "config/snakemake.yaml" 

rule all:
    input:
      expand("results/weather_year_{year_system}/postnetworks/operational/{year_weather}.nc", 
             year_system=[*range(1941, 2024, 1)], 
             year_weather=[*range(1941, 2024, 1)]) 

#rule all:
#    input:
#      expand("results/weather_year_{year_system}/postnetworks/operational/", year_system=[*range(1941, 2024, 1)])


#rule create_dir:
#    output:
#        directory("results/weather_year_{year_system}/postnetworks/operational/")
#    shell:
#        "mkdir -p {output}"

envvars:
	"GRB_LICENSE_FILE"

rule create_operational:
    input:
        "results/weather_year_{year_system}/postnetworks/elec_s_37_lv1.5__Co2L0-3H-T-H-B-I-A-dist1_2050.nc",
        "results/weather_year_{year_weather}/postnetworks/elec_s_37_lv1.5__Co2L0-3H-T-H-B-I-A-dist1_2050.nc"
    output:
        "results/weather_year_{year_system}/postnetworks/operational/{year_weather}.nc"
    threads: 4
    conda:
    	"envs/environment.yaml"
    resources: mem_mb=20000
    script:
        "scripts/run_multiple_weather_years.py"
	
        

